# Generated by Django 2.2.9 on 2020-04-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverImg', models.ImageField(upload_to='')),
                ('watermarkImg', models.ImageField(upload_to='')),
            ],
        ),
    ]
