# Generated by Django 2.2.9 on 2020-04-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermarkUsingDCT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watermark',
            name='coverImg',
            field=models.ImageField(upload_to='input/'),
        ),
        migrations.AlterField(
            model_name='watermark',
            name='watermarkImg',
            field=models.ImageField(upload_to='input/'),
        ),
    ]
